### PR TITLE
Implement ipaddress module in pingsweep.generateipaddress()

### PR DESCRIPTION
**Pull request by Slack3rr**
Regarding Issue #1

- Import ipaddress
- Replace generateipaddress() method

P.S.
This is my first PR!
If I committed any git sins sorry in advance.

### CODE REVIEW

**Comment by the-c0d3r** [comment]
Hi @Slack3rr, thanks for your PR. Your documentation is very comprehensive, in comparison, mine is barely readable since it was written so long ago. There is a few more things to do however, that is if you're up for it, if you're not, then I'll just merge and DIY. 
1. Modification of `generateipaddress()` to return a list of string ip address. It could be done by just `str(ipaddressObject)` I believe. 
2. The part about checking the ip endswith [line 153](https://github.com/the-c0d3r/pynmap/pull/3/commits/23dd0aa8ac34b67ab63162c6111185a1c1e6ace1#diff-8c1e136c8d901aa85fe1a9147c329265R153) can be improved to check the last octet. If you need ideas on how to do that, you can read my old `generateipaddress()` function, which does that manually. The reason this should be improved is that, when I tested with my laptop, my ipaddress's last octect is 220. Therefore it triggered error on the IPv4Network code. It apparently slipped through your check.

Lastly thanks again for your contribution. Let me know if you would like to continue this PR or should I merge it directly.

**Comment by Slack3rr** [comment]
Thank you for the compliment, I'm pretty new so it means a lot :p

I'd love to continue. I'll begin to implement your requests as soon as possible. It may take the day to complete because of work and such. I'll post if I'm having troubles. Otherwise, I'll get started and check back here periodically for any other requests. 

Thanks again!

**Comment by Slack3rr** [comment]
I think I got it. Let me know if I misinterpreted you and goofed up somewhere.

**Comment by the-c0d3r** [comment]
It's even better than my suggestion. I totally forgot about the host bits being different for different subnets. I'll test it out when I got home. Take your time, and feel free to question me if you got problems.

There's one additional suggestion since the host bits are gonna be different, currently the `generateipaddress()` takes in the subnet, but it'll be great if the function can automatically detect the subnet. This one will need to be handle somewhere in the program, so it's either detect the subnet outside, then call the `generateipaddress()` with the subnet or just pass the local ip and let the function handle the rest. 
I also looked around for that subnet calculation. Looks like ipaddress module may not support this. Most likely have to calculate manually. I'll look more into it. Feel free to take up the challenge 😀

**Comment by Slack3rr** [comment]
I'll give it a shot! 

I'm looking into ipaddress's documentation to get a better understanding and some ideas on finding the subnet. I'll likely need to ask questions...   : p

Also, I noticed the getlocalip() function, which supplies generateipaddress() with the ip, is returning a 'NoneType' as opposed to the list comprehension of socket.gethostname(). If you like, I'll begin working on this 'issue' as well.

P.S. Sorry for the late reply. I like to be prompt but I had to go for the weekend. 
: )

**Comment by the-c0d3r** [comment]
Hey thanks for your response, I really appreciate contributors and someone who can give me a second opinion. 
`getlocalip()` is a bit of a dirty hack to get local ip. I'll spend some time to do it in a better way. Can I ask how do you get a 'NoneType' in that function? Are you using python2 or python3? As well as your OS is linux or Darwin (macOS)? I tested it on my mac just now. It returns me a string of local IP, as it is supposed to. I'll look more into it tonight. And I have plans to refactor both `pingsweep.py` and `portscanner.py` to share common library files. I've already started work on this, although it's progressing a bit slow.

**Comment by Slack3rr** [comment]
- Python 2 (Although I prefer 3). It looked like that's the version you intended.
- Lubuntu VM ( Linux-4.15.0-29-generic-x86_64-with-Ubuntu-18.04-bionic )

If anything thank you. I'm looking to start my profile and a project like this is perfect for me. : )

Edit: 
Sorry I don't know why I refereed to list comprehension in the Darwin if condition. I guess I'm a little tired right now : p
It also appears that the platform check in getlocalip() isn't catching Linux. Changing, 'nix' -> 'Linux' on line 116 continues the function.

**Comment by the-c0d3r** [comment]
Nice catch. Previously I wanted to match all "linux" string, because on some OS, `sys.platform` returns "linux2" or "linux", it was supposed to be "nux" I think. I can't remember clearly why but I think the reason was to match all possible linux systems. I just did a quick check, on python3, it'll return just "linux". I'll edit it so that it maches all Linux distro.

As for the python version, yes it was targeted for python2 back then. But now it's time for me to migrate that to python3.

**Comment by Slack3rr** [comment]
O.K. Sounds good and I'll start focusing future code on python3.

**Comment by the-c0d3r** [comment]
Hey thanks a lot for your PR. I'll merge this first. If you have any more stuff to contribute, feel free to create another PR. 

I'm losing a bit confidence on the usefulness of this project already. I tested nmap (7.70) speed on my Arch Machine, the pingsweep finished within 3~4 seconds. Maybe I'll just focus more on changing the direction of this project to support multiple threaded/process mass scanner, instead of simple ping sweep or port scan. Maybe just make it function like a wrapper for nmap but with concurrency support. 

Btw if you wish to find more projects to contribute, you might want to take a look at my repositories. They are all not very complex.

**Comment by Slack3rr** [comment]
Hey thank YOU buddy. Like I said earlier this was a perfect starter project for me. I'm still getting used to git/github and working with others on code so this really helped. Having one merge under my belt helps my ego too lol ; )

I noticed the lack of performance as well. Figure we can work on that later ( I don't like giving up ; ) ). Extended functionality is a good focus for now. I like the idea of the extended concurrency support. I want to look into nmaps scan types documentation and see if anything can be improved, specifically  ARP packets and and what data is attached to them and other types of packets. Scapy maybe something to think about.

That something I'll do in my spare time. I'll definitely look into your other projects though. Let me know if you want anything specific for me to look into.

Thanks again!

**Comment by Slack3rr** [comment]
Hey, I posted my reply on the PR thread. I'll paste it here in case you didn't see it.

""

Hey thank YOU buddy. Like I said earlier this was a perfect starter project for me. I'm still getting used to git/github and working with others on code so this really helped. Having one merge under my belt helps my ego too lol ; )

I noticed the lack of performance as well. Figure we can work on that later ( I don't like giving up ; ) ). Extended functionality is a good focus for now. I like the idea of the extended concurrency support. I want to look into nmaps scan types documentation and see if anything can be improved, specifically ARP packets and and what data is attached to them and other types of packets. Scapy maybe something to think about.

That something I'll do in my spare time. I'll definitely look into your other projects though. Let me know if you want anything specific for me to look into.

Thanks again!

""

And of course,  Thanks again ; )
________________________________

**Pull request merged**
